module.exports = async (req, res) => {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { name, phone, matter, description } = req.body;

    if (!name || !phone || !matter) {
      return res.status(400).json({ error: 'Missing required fields' });
    }

    const apiKey = process.env.RESEND_API_KEY;
    if (!apiKey) {
      return res.status(500).json({ error: 'Resend API key is not configured' });
    }

    // Call Resend REST API using native fetch
    const response = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        from: 'Ritik Jayaswal Portfolio <onboarding@resend.dev>',
        to: ['ritikjayaswal2105@gmail.com'],
        subject: `New Inquiry from ${name} (${matter})`,
        html: `
          <div style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; border: 1px solid #eee; padding: 20px; border-radius: 8px;">
            <h2 style="color: #C8A96E; border-bottom: 2px solid #C8A96E; padding-bottom: 8px; margin-top: 0;">New Consultation Inquiry</h2>
            <p>You have received a new inquiry from your website contact form.</p>
            
            <table style="width: 100%; border-collapse: collapse; margin-top: 15px;">
              <tr>
                <td style="padding: 10px; border-bottom: 1px solid #eee; font-weight: bold; width: 150px; color: #555;">Name:</td>
                <td style="padding: 10px; border-bottom: 1px solid #eee; color: #333;">${name}</td>
              </tr>
              <tr>
                <td style="padding: 10px; border-bottom: 1px solid #eee; font-weight: bold; color: #555;">Phone:</td>
                <td style="padding: 10px; border-bottom: 1px solid #eee; color: #333;">${phone}</td>
              </tr>
              <tr>
                <td style="padding: 10px; border-bottom: 1px solid #eee; font-weight: bold; color: #555;">Matter Type:</td>
                <td style="padding: 10px; border-bottom: 1px solid #eee; color: #333; text-transform: capitalize;">${matter}</td>
              </tr>
            </table>

            <h3 style="color: #C8A96E; margin-top: 25px; margin-bottom: 10px;">Brief Description:</h3>
            <div style="background-color: #f9f9f9; border-left: 4px solid #C8A96E; padding: 15px; font-style: italic; color: #444; border-radius: 4px; white-space: pre-wrap;">${description || 'No description provided.'}</div>
            
            <p style="margin-top: 30px; font-size: 0.8em; color: #888; border-top: 1px solid #eee; padding-top: 15px; text-align: center;">This message was automatically generated by the contact form on your portfolio website.</p>
          </div>
        `,
      }),
    });

    const data = await response.json();

    if (!response.ok) {
      console.error('Resend API error response:', data);
      return res.status(response.status).json({ error: data.message || 'Failed to send email via Resend' });
    }

    return res.status(200).json({ success: true, data });
  } catch (error) {
    console.error('Server error handling contact request:', error);
    return res.status(500).json({ error: error.message || 'Internal server error' });
  }
};
